### PR TITLE
X1

### PR DESCRIPTION
**Pull request by ishidawataru**

### CODE REVIEW

**Comment by jnealtowns** [comment]
@ishidawataru I am working on fixing the KNET modules build now. If I get that working do you really still need the 3.16.39 kernel?

**Comment by ishidawataru** [comment]
No, I think we can use 4.14-lts

**Comment by jnealtowns** [comment]
We can still do the first version with the 3.16 kernel. If we really need to go back to the 3.16.39 version for initial compatibility I can just change the LTS patchlevel back to 39 in the 3.16-LTS config. 

I'm assuming you only needed that to match the kernel modules and if we fix that its all moot. Do you want to drop the 3.16.39 changes from the pull request?

**Comment by ishidawataru** [comment]
@jnealtowns Dropped 3.16.39 changes, added few more commits, also reflected a comment from @carlroth about tmp permission.

**Comment by jnealtowns** [comment]
Great thank you.

**Pull request merged**
